using System.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Agents;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.AzureOpenAI;
using OperationsCopilot.Agent.Options;
using OperationsCopilot.Agent.Planning;
using OperationsCopilot.Agent.Plugins;
using OperationsCopilot.Domain.Abstractions;
using OperationsCopilot.Domain.Chat;
using OperationsCopilot.Domain.Planning;
using OperationsCopilot.Infrastructure.Options;

// Both OpenAI.Chat and Microsoft.SemanticKernel define ChatMessageContent; alias the one
// type needed from the OpenAI package rather than importing the whole namespace.
using ChatTokenUsage = OpenAI.Chat.ChatTokenUsage;

namespace OperationsCopilot.Agent;

/// <summary>
/// The single Semantic Kernel agent behind <c>POST /api/chat</c>.
/// </summary>
/// <remarks>
/// <para>
/// There is no orchestration logic here on purpose. The kernel is given four tools and
/// <see cref="FunctionChoiceBehavior.Auto()"/>, and the model decides which to call and in what
/// order — including calling a database tool and the knowledge base in the same turn and
/// combining them. This class's job is to assemble the request, and to turn what happened into
/// an auditable response: the answer, the passages retrieved, the tools invoked, and the timings.
/// </para>
/// <para>
/// One thing is remembered between turns: the plan. When a question closely matches one asked
/// before, the tools that were chosen for it are replayed instead of being chosen again, which
/// removes the planning round trip. The tools themselves still run, so the figures are as current
/// as they would be otherwise — see <see cref="ISemanticPlanCache"/>.
/// </para>
/// </remarks>
public sealed class CopilotAgent(
    Kernel kernel,
    IToolCallRecorder recorder,
    IConversationStore conversationStore,
    ISemanticPlanCache planCache,
    PlanReplayer replayer,
    IOptions<CopilotAgentOptions> agentOptions,
    IOptions<SemanticCacheOptions> cacheOptions,
    TimeProvider timeProvider,
    ILogger<CopilotAgent> logger) : ICopilotAgent
{
    /// <summary>Citation excerpts are trimmed for display; the full passage stays in the database.</summary>
    private const int MaxExcerptLength = 400;

    private readonly CopilotAgentOptions _options = agentOptions.Value;
    private readonly SemanticCacheOptions _cache = cacheOptions.Value;

    public async Task<ChatResponse> AskAsync(
        ChatRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Message);

        var stopwatch = Stopwatch.StartNew();
        var conversationId = request.ConversationId is { Length: > 0 } id ? id : Guid.CreateVersion7().ToString("n");
        var askedAt = timeProvider.GetUtcNow();
        var today = DateOnly.FromDateTime(askedAt.UtcDateTime);

        var history = await conversationStore.GetHistoryAsync(conversationId, cancellationToken);
        var turn = await AnswerAsync(request.Message, conversationId, history, today, cancellationToken);

        stopwatch.Stop();

        await conversationStore.AppendAsync(
            conversationId,
            [
                new ChatTurn(ChatRole.User, request.Message, askedAt),
                new ChatTurn(ChatRole.Assistant, turn.Answer.Text, timeProvider.GetUtcNow()),
            ],
            cancellationToken);

        var toolCalls = recorder.ToolCalls;

        logger.LogInformation(
            "Answered conversation {ConversationId} in {LatencyMs}ms using {ToolCount} tool call(s) " +
            "and {CitationCount} passage(s); plan {PlanOrigin}.",
            conversationId,
            stopwatch.ElapsedMilliseconds,
            toolCalls.Count,
            recorder.RetrievedPassages.Count,
            turn.Cache?.Hit == true ? "reused from cache" : "generated by the model");

        return new ChatResponse(
            turn.Answer.Text,
            conversationId,
            BuildCitations(),
            toolCalls,
            stopwatch.ElapsedMilliseconds)
        {
            Usage = turn.Answer.Usage,
            PlanCache = turn.Cache,
        };
    }

    /// <summary>
    /// Decides how this turn is answered: by replaying a cached plan, or by asking the model for
    /// one — and, in the second case, whether the plan it produced is worth keeping.
    /// </summary>
    private async Task<TurnResult> AnswerAsync(
        string message,
        string conversationId,
        IReadOnlyList<ChatTurn> history,
        DateOnly today,
        CancellationToken cancellationToken)
    {
        if (!_cache.Enabled)
        {
            return new TurnResult(await PlanAndAnswerAsync(message, conversationId, history, cancellationToken), null);
        }

        // A follow-up is not a question on its own. "And in Rotterdam?" means nothing without the
        // turn before it, so its embedding is not a key that identifies anything, and a plan
        // stored under it would be reused for unrelated conversations that happen to say the same
        // three words. First turns only, in both directions.
        if (history.Count > 0)
        {
            var followUp = await PlanAndAnswerAsync(message, conversationId, history, cancellationToken);

            return new TurnResult(
                followUp,
                new PlanCacheTrace(Hit: false)
                {
                    Note = "Follow-up turns depend on the conversation, so the cache was not used.",
                });
        }

        var hit = await planCache.FindAsync(message, today, cancellationToken);

        if (hit is not null && replayer.CanReplay(hit.Plan))
        {
            var replayed = await ReplayAndAnswerAsync(message, conversationId, hit, cancellationToken);
            await planCache.RecordReuseAsync(hit.EntryId, cancellationToken);

            return new TurnResult(
                replayed,
                new PlanCacheTrace(Hit: true)
                {
                    Similarity = hit.Similarity,
                    MatchedQuestion = hit.MatchedQuestion,
                    PlanCapturedAt = hit.CapturedAt,
                    TimesReused = hit.TimesReused,
                });
        }

        string? discarded = null;

        if (hit is not null)
        {
            logger.LogWarning(
                "Discarding the cached plan for {Question}: it names a tool that no longer exists.",
                hit.MatchedQuestion);

            await planCache.RemoveAsync(hit.EntryId, cancellationToken);
            discarded = "A stored plan named a tool that no longer exists and was discarded.";
        }

        var answer = await PlanAndAnswerAsync(message, conversationId, history, cancellationToken);
        var (stored, reason) = await TryStoreAsync(message, today, cancellationToken);

        return new TurnResult(
            answer,
            new PlanCacheTrace(Hit: false)
            {
                Stored = stored,
                Note = discarded ?? reason,
            });
    }

    /// <summary>The normal path: the model is given the tools and decides for itself.</summary>
    private async Task<AgentAnswer> PlanAndAnswerAsync(
        string message,
        string conversationId,
        IReadOnlyList<ChatTurn> history,
        CancellationToken cancellationToken)
    {
        var thread = BuildThread(conversationId, history);

        return await InvokeAsync(BuildAgent(withTools: true), thread, message, cancellationToken);
    }

    /// <summary>
    /// The cached path: run the remembered tools, then ask the model to write the answer from
    /// what they returned.
    /// </summary>
    /// <remarks>
    /// The model is offered no tools at all on this call, rather than being told not to use them.
    /// Skipping the round trip but still paying for the tool catalogue in the prompt would give
    /// up most of what the cache is for.
    /// </remarks>
    private async Task<AgentAnswer> ReplayAndAnswerAsync(
        string message,
        string conversationId,
        PlanCacheHit hit,
        CancellationToken cancellationToken)
    {
        var replayed = await replayer.ExecuteAsync(hit.Plan, cancellationToken);
        var thread = BuildThread(conversationId, [], CopilotSystemPrompt.BuildReplayedEvidence(replayed));

        return await InvokeAsync(BuildAgent(withTools: false), thread, message, cancellationToken);
    }

    /// <summary>
    /// Stores this turn's plan, unless the turn is one whose plan should not be trusted later.
    /// </summary>
    /// <returns>Whether it was stored, and why not when it wasn't.</returns>
    private async Task<(bool Stored, string? Reason)> TryStoreAsync(
        string question,
        DateOnly today,
        CancellationToken cancellationToken)
    {
        var calls = recorder.PlannedCalls;

        if (calls.Count == 0)
        {
            return (false, "The agent answered without calling a tool, so there was no plan to cache.");
        }

        if (recorder.ToolCalls.Any(call => !call.Succeeded))
        {
            return (false, "A tool failed this turn, so its plan was not cached.");
        }

        // A turn that hit the budget was cut short by the filter, and what it managed to call is
        // a truncated plan rather than a good one. Caching it would make the truncation permanent.
        if (recorder.ToolCalls.Count >= _options.MaxToolCallsPerTurn)
        {
            return (false, "The turn reached the tool call budget, so its plan was not cached.");
        }

        await planCache.StoreAsync(question, new ToolPlan(calls), today, cancellationToken);

        return (true, null);
    }

    private ChatCompletionAgent BuildAgent(bool withTools)
    {
        var today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);

        return new ChatCompletionAgent
        {
            Name = _options.Name,
            Description = "Answers questions about Aurora Supply Co. stock, sales, products and policy.",
            Instructions = CopilotSystemPrompt.Build(today, _options.AdditionalInstructions),
            Kernel = withTools ? kernel : kernel.WithoutTools(),
            Arguments = new KernelArguments(new AzureOpenAIPromptExecutionSettings
            {
                // Auto is the whole point of the demo: the model picks the tools, not us. None is
                // for the replay path, where they were picked on an earlier turn.
                FunctionChoiceBehavior = withTools
                    ? FunctionChoiceBehavior.Auto()
                    : FunctionChoiceBehavior.None(),
                Temperature = _options.Temperature,
                MaxTokens = _options.MaxOutputTokens,
            }),
        };
    }

    private static ChatHistoryAgentThread BuildThread(
        string conversationId,
        IReadOnlyList<ChatTurn> turns,
        string? evidence = null)
    {
        var history = new ChatHistory();

        foreach (var turn in turns)
        {
            history.Add(new ChatMessageContent(
                turn.Role == ChatRole.User ? AuthorRole.User : AuthorRole.Assistant,
                turn.Content));
        }

        if (!string.IsNullOrWhiteSpace(evidence))
        {
            history.Add(new ChatMessageContent(AuthorRole.System, evidence));
        }

        return new ChatHistoryAgentThread(history, conversationId);
    }

    private static async Task<AgentAnswer> InvokeAsync(
        ChatCompletionAgent agent,
        AgentThread thread,
        string message,
        CancellationToken cancellationToken)
    {
        var text = new List<string>();
        var promptTokens = 0;
        var completionTokens = 0;

        await foreach (var item in agent.InvokeAsync(message, thread, options: null, cancellationToken))
        {
            if (!string.IsNullOrWhiteSpace(item.Message.Content))
            {
                text.Add(item.Message.Content);
            }

            // Tool rounds each produce their own completion; usage has to be summed across them
            // or the reported cost of a multi-tool answer is understated.
            if (TryReadUsage(item.Message.Metadata, out var usage))
            {
                promptTokens += usage.InputTokenCount;
                completionTokens += usage.OutputTokenCount;
            }
        }

        var answer = text.Count > 0
            ? string.Join("\n\n", text).Trim()
            : "I could not produce an answer for that. Try rephrasing the question.";

        return new AgentAnswer(
            answer,
            promptTokens + completionTokens > 0 ? new TokenUsage(promptTokens, completionTokens) : null);
    }

    private static bool TryReadUsage(
        IReadOnlyDictionary<string, object?>? metadata,
        out ChatTokenUsage usage)
    {
        if (metadata is not null
            && metadata.TryGetValue("Usage", out var raw)
            && raw is ChatTokenUsage reported)
        {
            usage = reported;
            return true;
        }

        usage = null!;
        return false;
    }

    /// <summary>
    /// Turns the passages retrieved this turn into citations, numbered in the same order the
    /// model saw them so a <c>[2]</c> in the answer text resolves to citation 2 here.
    /// </summary>
    private IReadOnlyList<Citation> BuildCitations()
    {
        var passages = recorder.RetrievedPassages;

        return [.. passages.Select((passage, index) => new Citation(
            CitationReference.At(index),
            passage.SourceFile,
            passage.DocumentTitle,
            passage.Heading,
            Excerpt(passage.Content),
            Math.Round(passage.Score, 4)))];
    }

    private static string Excerpt(string content)
    {
        var normalized = content.ReplaceLineEndings(" ").Trim();

        return normalized.Length <= MaxExcerptLength
            ? normalized
            : normalized[..MaxExcerptLength].TrimEnd() + "…";
    }

    private sealed record AgentAnswer(string Text, TokenUsage? Usage);

    private sealed record TurnResult(AgentAnswer Answer, PlanCacheTrace? Cache);
}
